// Static skill catalog sourced from skills.sh top skills by install count.
// source format: "org/repo" — the server resolves this to https://github.com/org/repo
// importKey: "org/repo/skillId" — passed directly to importFromSource()

export interface SkillCatalogEntry {
  skillId: string;
  source: string;       // "org/repo"
  importKey: string;    // "org/repo/skillId" — ready for importFromSource()
  name: string;
  description: string;
  category: string;
  tags: string[];
  installs: number;
}

export const SKILL_CATALOG: SkillCatalogEntry[] = [
  // ── Development ────────────────────────────────────────────────────────────
  {
    skillId: "claude-code-basics",
    source: "anthropics/claude-code",
    importKey: "anthropics/claude-code/claude-code-basics",
    name: "Claude Code Basics",
    description: "Core patterns for working with Claude Code: file editing, bash commands, and agentic coding best practices.",
    category: "Development",
    tags: ["coding", "claude", "ai", "core"],
    installs: 33568,
  },
  {
    skillId: "frontend-design",
    source: "anthropics/claude-code",
    importKey: "anthropics/claude-code/frontend-design",
    name: "Frontend Design",
    description: "Build polished, responsive UIs with modern CSS, component patterns, and design-system best practices.",
    category: "Development",
    tags: ["frontend", "css", "ui", "design"],
    installs: 32669,
  },
  {
    skillId: "nodejs-backend-patterns",
    source: "wshobson/agents",
    importKey: "wshobson/agents/nodejs-backend-patterns",
    name: "Node.js Backend Patterns",
    description: "Best-practice patterns for Node.js APIs: error handling, middleware, async patterns, and project structure.",
    category: "Development",
    tags: ["nodejs", "backend", "api", "javascript"],
    installs: 29411,
  },
  {
    skillId: "api-design-principles",
    source: "wshobson/agents",
    importKey: "wshobson/agents/api-design-principles",
    name: "API Design Principles",
    description: "RESTful API design: versioning, resource naming, error responses, pagination, and OpenAPI documentation.",
    category: "Development",
    tags: ["api", "rest", "openapi", "design"],
    installs: 18790,
  },
  {
    skillId: "nextjs-app-router-patterns",
    source: "wshobson/agents",
    importKey: "wshobson/agents/nextjs-app-router-patterns",
    name: "Next.js App Router Patterns",
    description: "Patterns for the Next.js App Router: server components, streaming, layouts, and data fetching strategies.",
    category: "Development",
    tags: ["nextjs", "react", "frontend", "fullstack"],
    installs: 15085,
  },
  {
    skillId: "postgresql-table-design",
    source: "wshobson/agents",
    importKey: "wshobson/agents/postgresql-table-design",
    name: "PostgreSQL Table Design",
    description: "Database schema design principles: normalization, indexing strategies, constraints, and query optimization.",
    category: "Development",
    tags: ["postgres", "database", "sql", "schema"],
    installs: 15069,
  },
  {
    skillId: "architecture-patterns",
    source: "wshobson/agents",
    importKey: "wshobson/agents/architecture-patterns",
    name: "Architecture Patterns",
    description: "Software architecture patterns: microservices, event-driven design, CQRS, hexagonal architecture, and DDD.",
    category: "Development",
    tags: ["architecture", "design-patterns", "backend", "system-design"],
    installs: 13872,
  },
  {
    skillId: "python-performance-optimization",
    source: "wshobson/agents",
    importKey: "wshobson/agents/python-performance-optimization",
    name: "Python Performance Optimization",
    description: "Profile and optimize Python code: async patterns, memory management, vectorization, and caching strategies.",
    category: "Development",
    tags: ["python", "performance", "optimization", "backend"],
    installs: 19861,
  },
  {
    skillId: "error-handling-patterns",
    source: "wshobson/agents",
    importKey: "wshobson/agents/error-handling-patterns",
    name: "Error Handling Patterns",
    description: "Robust error handling: structured logging, custom error types, retry logic, and graceful degradation.",
    category: "Development",
    tags: ["errors", "resilience", "logging", "backend"],
    installs: 10266,
  },
  // ── Testing & Quality ───────────────────────────────────────────────────────
  {
    skillId: "tdd",
    source: "mattpocock/skills",
    importKey: "mattpocock/skills/tdd",
    name: "Test-Driven Development",
    description: "TDD workflows: writing failing tests first, red-green-refactor cycles, and test coverage strategies.",
    category: "Testing",
    tags: ["tdd", "testing", "quality", "unit-tests"],
    installs: 19205,
  },
  {
    skillId: "e2e-testing-patterns",
    source: "wshobson/agents",
    importKey: "wshobson/agents/e2e-testing-patterns",
    name: "E2E Testing Patterns",
    description: "End-to-end test patterns with Playwright and Cypress: page objects, fixtures, CI integration, and flake prevention.",
    category: "Testing",
    tags: ["e2e", "playwright", "testing", "automation"],
    installs: 13905,
  },
  {
    skillId: "code-review-excellence",
    source: "wshobson/agents",
    importKey: "wshobson/agents/code-review-excellence",
    name: "Code Review Excellence",
    description: "Structured code review: security checks, performance review, readability standards, and constructive feedback patterns.",
    category: "Testing",
    tags: ["code-review", "quality", "security", "collaboration"],
    installs: 14135,
  },
  {
    skillId: "security-best-practices",
    source: "supercent-io/skills-template",
    importKey: "supercent-io/skills-template/security-best-practices",
    name: "Security Best Practices",
    description: "Application security: OWASP top-10 mitigations, input validation, auth patterns, and secrets management.",
    category: "Testing",
    tags: ["security", "owasp", "auth", "hardening"],
    installs: 14119,
  },
  {
    skillId: "accessibility",
    source: "addyosmani/web-quality-skills",
    importKey: "addyosmani/web-quality-skills/accessibility",
    name: "Web Accessibility",
    description: "WCAG 2.1 compliance: semantic HTML, ARIA roles, keyboard navigation, color contrast, and screen reader support.",
    category: "Testing",
    tags: ["accessibility", "a11y", "wcag", "frontend"],
    installs: 19658,
  },
  // ── DevOps ──────────────────────────────────────────────────────────────────
  {
    skillId: "docker-expert",
    source: "sickn33/antigravity-awesome-skills",
    importKey: "sickn33/antigravity-awesome-skills/docker-expert",
    name: "Docker Expert",
    description: "Docker best practices: multi-stage builds, layer optimization, compose patterns, and container security.",
    category: "DevOps",
    tags: ["docker", "containers", "devops", "ci"],
    installs: 13580,
  },
  {
    skillId: "git-commit",
    source: "github/awesome-copilot",
    importKey: "github/awesome-copilot/git-commit",
    name: "Git Commit Conventions",
    description: "Conventional commits, semantic versioning, branch strategies, and clean commit message guidelines.",
    category: "DevOps",
    tags: ["git", "commits", "versioning", "devops"],
    installs: 26942,
  },
  {
    skillId: "gh-cli",
    source: "github/awesome-copilot",
    importKey: "github/awesome-copilot/gh-cli",
    name: "GitHub CLI",
    description: "Automate GitHub workflows with gh CLI: PRs, issues, releases, and Actions from the command line.",
    category: "DevOps",
    tags: ["github", "cli", "automation", "devops"],
    installs: 19427,
  },
  // ── Writing & Docs ──────────────────────────────────────────────────────────
  {
    skillId: "documentation-writer",
    source: "github/awesome-copilot",
    importKey: "github/awesome-copilot/documentation-writer",
    name: "Documentation Writer",
    description: "Write clear technical documentation: READMEs, API docs, runbooks, and architecture decision records.",
    category: "Writing",
    tags: ["docs", "technical-writing", "readme", "markdown"],
    installs: 15890,
  },
  {
    skillId: "write-a-prd",
    source: "mattpocock/skills",
    importKey: "mattpocock/skills/write-a-prd",
    name: "Write a PRD",
    description: "Structure and write product requirements documents: user stories, acceptance criteria, and scope definition.",
    category: "Writing",
    tags: ["prd", "product", "requirements", "planning"],
    installs: 14235,
  },
  {
    skillId: "internal-comms",
    source: "anthropics/skills",
    importKey: "anthropics/skills/internal-comms",
    name: "Internal Communications",
    description: "Draft effective internal memos, announcements, meeting summaries, and team updates with clear structure.",
    category: "Writing",
    tags: ["communications", "writing", "memos", "meetings"],
    installs: 28549,
  },
  {
    skillId: "brand-guidelines",
    source: "anthropics/skills",
    importKey: "anthropics/skills/brand-guidelines",
    name: "Brand Guidelines",
    description: "Maintain brand consistency: voice and tone, visual guidelines, messaging frameworks, and content standards.",
    category: "Writing",
    tags: ["brand", "design", "marketing", "consistency"],
    installs: 32420,
  },
  {
    skillId: "refactor",
    source: "github/awesome-copilot",
    importKey: "github/awesome-copilot/refactor",
    name: "Refactoring Patterns",
    description: "Code refactoring techniques: extract methods, reduce duplication, improve naming, and increase cohesion.",
    category: "Writing",
    tags: ["refactoring", "clean-code", "quality", "patterns"],
    installs: 14697,
  },
  {
    skillId: "improve-codebase-architecture",
    source: "mattpocock/skills",
    importKey: "mattpocock/skills/improve-codebase-architecture",
    name: "Improve Codebase Architecture",
    description: "Identify and resolve architectural problems: dependency inversion, module boundaries, and tech debt reduction.",
    category: "Development",
    tags: ["architecture", "refactoring", "design", "quality"],
    installs: 15303,
  },
  // ── Marketing ───────────────────────────────────────────────────────────────
  {
    skillId: "sales-enablement",
    source: "coreyhaines31/marketingskills",
    importKey: "coreyhaines31/marketingskills/sales-enablement",
    name: "Sales Enablement",
    description: "Create sales collateral, pitch decks, one-pagers, objection handling guides, and competitive battle cards.",
    category: "Marketing",
    tags: ["sales", "marketing", "enablement", "content"],
    installs: 33523,
  },
  {
    skillId: "revops",
    source: "coreyhaines31/marketingskills",
    importKey: "coreyhaines31/marketingskills/revops",
    name: "Revenue Operations",
    description: "RevOps workflows: pipeline reporting, funnel analysis, CRM hygiene, and go-to-market alignment.",
    category: "Marketing",
    tags: ["revops", "sales", "analytics", "crm"],
    installs: 32510,
  },
  {
    skillId: "customer-research",
    source: "coreyhaines31/marketingskills",
    importKey: "coreyhaines31/marketingskills/customer-research",
    name: "Customer Research",
    description: "User interviews, surveys, persona development, JTBD frameworks, and synthesis of qualitative insights.",
    category: "Marketing",
    tags: ["research", "ux", "personas", "marketing"],
    installs: 18571,
  },
  {
    skillId: "lead-magnets",
    source: "coreyhaines31/marketingskills",
    importKey: "coreyhaines31/marketingskills/lead-magnets",
    name: "Lead Magnets",
    description: "Design and write high-converting lead magnets: guides, checklists, calculators, and email sequences.",
    category: "Marketing",
    tags: ["lead-gen", "content", "marketing", "conversion"],
    installs: 26613,
  },
  // ── Data & Search ────────────────────────────────────────────────────────────
  {
    skillId: "data-analysis",
    source: "supercent-io/skills-template",
    importKey: "supercent-io/skills-template/data-analysis",
    name: "Data Analysis",
    description: "Analyze datasets, produce summaries, identify trends, and generate charts and actionable insights.",
    category: "Data",
    tags: ["data", "analytics", "reporting", "insights"],
    installs: 13831,
  },
  {
    skillId: "tavily-search",
    source: "tavily-ai/skills",
    importKey: "tavily-ai/skills/tavily-search",
    name: "Tavily Web Search",
    description: "AI-optimized web search via the Tavily API: real-time results, source attribution, and research automation.",
    category: "Data",
    tags: ["search", "web", "research", "api"],
    installs: 14136,
  },
  {
    skillId: "seo",
    source: "addyosmani/web-quality-skills",
    importKey: "addyosmani/web-quality-skills/seo",
    name: "SEO Optimization",
    description: "On-page SEO: meta tags, structured data, Core Web Vitals, keyword research, and technical SEO audits.",
    category: "Data",
    tags: ["seo", "search", "marketing", "web"],
    installs: 19442,
  },
];

export const SKILL_CATEGORIES = [...new Set(SKILL_CATALOG.map((s) => s.category))].sort();
